### PR TITLE
Upgrade to latest version

### PR DESCRIPTION
**Pull request by Alecaddd**
Upgrade to v0.6.9

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
Somehow the build failed on aarch64. I have triggered a new build.

**Comment by Alecaddd** [comment]
@bilelmoussaoui this might be related to the `libfixposix` dependency as a user reported that he was having troubles building it on arch from source. I will release a patched version soon.

**Comment by Alecaddd** [comment]
Mh, that's weird, I've no idea why it's failing on aarch64.
I'm not suing the `libfixposix` anymore, but I'm not sure if that has anything to do with it.

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Pull request merged**
