### PR TITLE
Bump to Juno BaseApp

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by nedrichards** [comment]
build still fails: https://flathub.org/builds/#/builders/2/builds/5661

**Comment by bilelmoussaoui** [comment]
Yeah I triggered a new build just to see why it fails again. My laptop is too slow to build libgda :(

**Comment by bilelmoussaoui** [comment]
It builds just fine here. Let me trigger an other test build.

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
Finally got this fixed

**Pull request merged**
