### PR TITLE
Update libgda to 5.2.5

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
@Alecaddd Have you had the time to play with the new version of libgda? It works without any issues here. Going to push it to the flatpak package as it has some underhood improvements.

**Comment by bilelmoussaoui** [comment]
Builds perfectly https://flathub.org/builds/#/builders/2/builds/4837

**Comment by Alecaddd** [comment]
Didn't have time to install it on my machine and test it. It shouldn't be any problem as it's a maintenance release and doesn't break/deprecate any of the previous API.
I'd say go ahead and merge it. Flatpak is gonna have a sweet new addition before the main release XD

**Comment by bilelmoussaoui** [comment]
Merged! :+1:

**Pull request merged**
