### PR TITLE
Upgrade to v0.6.2

### PR DESCRIPTION
**Pull request by Alecaddd**

### CODE REVIEW

**Comment by Alecaddd** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
Okay that fixed the build here https://flathub.org/builds/#/builders/2/builds/4714
Do you think that we should force the elementary gtk/icon theme?

**Comment by Alecaddd** [comment]
Do you mean inside the FlatPak build? If possible and it doesn't weight a ton, it would be great for the visual consistency.
What you think is the best I'm ok with it.

**Comment by bilelmoussaoui** [comment]
bot, build

**Pull request merged**
