### PR TITLE
Bump to 42

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by yakushabb** [comment]
https://flathub.org/apps/com.github.alecaddd.sequeler says "Uses an end-of-life runtime" hovewer it seems you have updated the runtime version to 46.

Do you have any idea about it?

**Comment by alatiera** [comment]
The build has been failing to publish in flathub due to infrastructure issues.

**Pull request merged**
